WIDTH = 1000
HEIGHT = 800
FPS = 10

F_RADIUS = 20
S_THICK = F_RADIUS * 2


START_X = S_THICK * ((WIDTH // 4) // S_THICK)
START_Y = S_THICK * ((HEIGHT // 4) // S_THICK)

LEFT = (-1, 0)
RIGHT = (1, 0)
UP = (0, -1)
DOWN = (0, 1)
